### ISSUE TITLE
textNode scope issue with causes checkBufferLength to throw

### ISSUE THREAD

**Issue by christian-bromann** [jimhigson/oboe.js#157]
I am running oboe.js to parse json files with sizes of multiple 100MBs. Every once in a while I receive error notifications with the following message:

```
/usr/app/node_modules/oboe/dist/oboe-node.js:610
  maxActual = Math.max(maxActual, textNode.length);
                                                 ^
                                                 TypeError: Cannot read property 'length' of undefined
at checkBufferLength (/usr/app/node_modules/oboe/dist/oboe-node.js:610:48)
at handleData (/usr/app/node_modules/oboe/dist/oboe-node.js:1027:7)
at applyEach (/usr/app/node_modules/oboe/dist/oboe-node.js:496:20)
at Object.emit (/usr/app/node_modules/oboe/dist/oboe-node.js:1931:7)
at Request.<anonymous> (/usr/app/node_modules/oboe/dist/oboe-node.js:1130:34)
at emitOne (events.js:121:20)
at Request.emit (events.js:211:7)
at IncomingMessage.<anonymous> (/usr/app/node_modules/request/request.js:1082:12)
at emitOne (events.js:121:20)
at IncomingMessage.emit (events.js:211:7)
```
Which is weird because `checkBufferLength` actually has an undefined check:
```js
    // ...
    if (textNode !== undefined && textNode.length > MAX_BUFFER_LENGTH) {
      emitError("Max buffer length exceeded: textNode");
      maxActual = Math.max(maxActual, textNode.length);
    }
    // ...
```
So I assume that the value of `textNode` must have changed after it was evaluated in the if condition. I guess the simples fix would be to clone the value of `textNode` in `checkBufferLength` to prevent this from happening. What would you think? Happy to provide a PR and have it running in my cluster to check if it actually fixes the issue.

**Comment by christian-bromann** [comment]
On that note, would you think it makes sense to make `MAX_BUFFER_LENGTH` an oboe.js option?

**Comment by christian-bromann** [comment]
After some more digging it seems that `emitError` sets `textNode` back to undefined. So it is not exactly an scope issue but still a bug.

**Comment by mweimer** [comment]
This is similar to #101,  I submitted a PR to make the max buffer size and check optional, since there may be cases where you don't know how big your json strings might be.
