### ISSUE TITLE
Node.js: Doesn't work with http.IncomingMessage stream

### ISSUE THREAD

**Issue by initrunlevel0** [jimhigson/oboe.js#40]
I am still working to implement oboe.js for stream-based JSON upload in my web application. The uploaded JSON file will be very large (some gigabyte) and processed directly into MongoDB without buffering all of it inside memory (that ain't fit)

I found out that oboe.js detected http.IncomingMessage (which is an implementation of ReadableStream used to receive the uploaded data) as an ordinary URL because it has field called "url" and oboe.js assuming that it is an ordinary URL, thus my web application return an error like this : 

```
/mnt/data/Dropbox/Journal/2013B/SISTER/DewaSister/FP/node_modules/oboe/dist/oboe-node.js:1093
         throw new Error(
               ^
Error: Supported protocols when passing a URL into Oboe are http and https. If you wish to use another protocol, please pass a ReadableStream (ht
tp://nodejs.org/api/stream.html#stream_class_stream_readable) like oboe(fs.createReadStream("my_file")). I was given the URL: /
    at fetchUrl (/mnt/data/Dropbox/Journal/2013B/SISTER/DewaSister/FP/node_modules/oboe/dist/oboe-node.js:1093:16)
    at streamingHttp (/mnt/data/Dropbox/Journal/2013B/SISTER/DewaSister/FP/node_modules/oboe/dist/oboe-node.js:1141:7)
    at wire (/mnt/data/Dropbox/Journal/2013B/SISTER/DewaSister/FP/node_modules/oboe/dist/oboe-node.js:2349:7)
    at applyDefaults (/mnt/data/Dropbox/Journal/2013B/SISTER/DewaSister/FP/node_modules/oboe/dist/oboe-node.js:2407:11)
    at oboe (/mnt/data/Dropbox/Journal/2013B/SISTER/DewaSister/FP/node_modules/oboe/dist/oboe-node.js:2419:17)
    at Server.<anonymous> (/mnt/data/Dropbox/Journal/2013B/SISTER/DewaSister/FP/bermainStream.js:5:5)
    at Server.EventEmitter.emit (events.js:104:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:505:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:358:22)
```

**Comment by Aigeec** [comment]
Was attempting to use oboe on a project I am testing with Jest. Jest seems to do weird things to the EventEmitter in node environments such that `EventEmitter instanceof Object` does not return true.

The net effect of this is that you cannot test code that uses Oboe with Jest.

The issue is with this [line of code](https://github.com/jimhigson/oboe.js/blob/3c1199e737f1f0b9ea916996a368a6d1a60a1750/src/util.js#L37) here where when duck typing to check if its a stream it is first checking if it is an `instanceof Object`. Simply changing that to `typeof o === 'object'` works. 

https://repl.it/@Aigeec/Jest-thinks-EventEmitter-is-not-an-object
https://repl.it/@Aigeec/Node-thinks-EventEmitter-is-an-object

I will raise an issue with Jest too of course but thought I would let you know.
