### ISSUE TITLE
Invalid symbol in number

### ISSUE THREAD

**Issue by retorquere** [jimhigson/oboe.js#84]
I'm trying to parse a big (110mb) JSON file, but I'm getting an error. The script I use to parse the JSON file is at https://gist.github.com/b57be8d0e2bdb3174432; I have a clarinet parsing pass above the oboe pass just to see if it would fail too, but it passes, where the oboe pass this fails with 

```
{ statusCode: undefined,
  body: undefined,
  jsonBody: undefined,
  thrown: 
   [Error: Invalid symbol in number
   Ln: 7049418
   Col: 20
   Chr: -] }
```

On line 7049418 there is:

```
  [-4.900000183e-09],
```

but there are more lines like these, and if I trim out the surrounding objects in the array, it does pass. The file is big (110Mb) so I can't attach it here

The file looks to be valid JSON; python parses it without incident.

**Comment by JuanCaicedo** [comment]
I think there might be something else wrong with your JSON, could you give some more details about it? 
I tried parsing the following and had no problem
```json
[{
  "index": 105,
  "action": "draw",
  "x": [-4.900000183e-09],
  "y": 7
}]
```

**Comment by retorquere** [comment]
I can use node `require` to load it, and `data = JSON.parse(fs.readFileSync(datafile))` also works. What details would help?

**Comment by JuanCaicedo** [comment]
I'd love to have a JSON to test against that's the same form as yours, but smaller. Like if it's an array, trimming it down to just one object. 

For the gist you posted, is that in node or in the browser?

**Comment by retorquere** [comment]
That's in node.

Unfortunately it seems to be related to the file size in some way. If I trim the JSON to the object that contains the line in the error, the error goes away.

Can I share the file privately with you?

**Comment by JuanCaicedo** [comment]
Sure, let's try that! You can use whatever method you prefer and send it to the email I have listed on my profile.

**Comment by retorquere** [comment]
Done, you should have mail now.

**Comment by JuanCaicedo** [comment]
@retorquere after running your example code against that file, I don't have any errors. I see it start printing out arrays to this console. 

I'm trying to think of what else could be different. 

- What version of node are you using? 
- What version of oboe are you using?
- What's the encoding on that data file?

**Comment by retorquere** [comment]
Node version: 5.3.0
oboe: 2.1.2
encoding: UTF-8 (I think), established as follows:

```
$ pcregrep -n '[^\x00-\x7F]' 2015-10-14---2016-01-06--4-ZTB-51.json  > /tmp/tt
$ file /tmp/tt
/tmp/tt: UTF-8 Unicode text, with CRLF line terminators
```

**Comment by JuanCaicedo** [comment]
I tested this with v0.10.36, so I can try other versions of Node and see if this is a regression. If you want to try this as well, let me know what you find.

**Comment by retorquere** [comment]
Sure, do you know offhand how I install a parallel version on osx or Linux?

**Comment by JuanCaicedo** [comment]
The best way I know it to use [nvm](https://github.com/creationix/nvm). It might be possible to do this without uninstalling your current version of node, though maybe not.

**Comment by mwlon** [comment]
I'm encountering the same issue, but with a + instead of -. My json can be parsed by python and node's default parsers, but not oboe.

json size: 228MB
error: `{ statusCode: undefined,
  body: undefined,
  jsonBody: undefined,
  thrown: 
   Error: Invalid symbol in number
   Ln: 1
   Col: 6487441
   Chr: +
       at emitError (.../node_modules/oboe/dist/oboe-node.js:635:20)
       at handleData (.../node_modules/oboe/dist/oboe-node.js:1007:23)
       at applyEach (.../node_modules/oboe/dist/oboe-node.js:496:20)
       at Object.emit (.../node_modules/oboe/dist/oboe-node.js:1929:10)
       at ReadStream.<anonymous> (.../node_modules/oboe/dist/oboe-node.js:1128:34)
       at emitOne (events.js:115:13)
       at ReadStream.emit (events.js:210:7)
       at addChunk (_stream_readable.js:250:12)
       at readableAddChunk (_stream_readable.js:237:11)
       at ReadStream.Readable.push (_stream_readable.js:195:10)
       at onread (fs.js:1991:12) }`
oboe version: 2.1.3
node version: 8.0.0

The specified column is actually in the middle of a very long string. However, my json does include nodes of the form `{"rarity": 2.0196912382954304e+17}`.

I'm not sure what's causing the bug, but the wrong column reporting seems to be because column isn't incremented in string processing: https://github.com/jimhigson/oboe.js/blob/master/dist/oboe-node.js#L835

**Comment by mwlon** [comment]
I have a 2-line fix for this bug. @JuanCaicedo can I get permission to make a PR?

**Comment by JuanCaicedo** [comment]
@mwlon Yeah, go ahead! I'll try to figure out how to incorporate it, though I'm not familiar with how to make changes to the project 😕

**Comment by mwlon** [comment]
@JuanCaicedo Excellent. I don't have permission to push to a branch or make a pull request, though, and would need those. It looks like you're the only one merging PRs here in the last 2 years, so you're the right person to ask, right?

**Comment by mwlon** [comment]
If you can't figure out the permissions stuff, I can also just tell you the code change.

**Comment by mwlon** [comment]
PR: https://github.com/jimhigson/oboe.js/pull/145
